substitutions:
  uuid: # based on uuid source https://github.com/sandeepmistry/node-tethercell/blob/master/tethercell.txt
    service: 5EC0FFF0-3CF2-A682-E211-2AF96EFDF667
    family: 5EC0FFF1-3CF2-A682-E211-2AF96EFDF667
    fet_state: 5EC0FFF2-3CF2-A682-E211-2AF96EFDF667
    battery_voltage: 5EC0FFF3-3CF2-A682-E211-2AF96EFDF667
    timers: 5EC0FFF4-3CF2-A682-E211-2AF96EFDF667
    timer_access_index: 5EC0FFF5-3CF2-A682-E211-2AF96EFDF667
    battery_voltage_most_recent_index: 5EC0FFF6-3CF2-A682-E211-2AF96EFDF667
    battery_voltage_history: 5EC0FFF7-3CF2-A682-E211-2AF96EFDF667
    password: 5EC0FFF8-3CF2-A682-E211-2AF96EFDF667
    device_name: 5EC0FFF9-3CF2-A682-E211-2AF96EFDF667
    utc_time: 5EC0FFFA-3CF2-A682-E211-2AF96EFDF667
    advertising_period: 5EC0FFFB-3CF2-A682-E211-2AF96EFDF667
    authorization: 5EC0FFFC-3CF2-A682-E211-2AF96EFDF667

ble_client:
  - mac_address: ${tethercell_mac}
    id: tethercell_device_${tethercell_number}
    auto_connect: true
    on_connect:
      then:
        - lambda: |-
            ESP_LOGI("ble_client_lambda", "Client connected to Tethercell ${tethercell_number}");
        - lambda: |-
            ESP_LOGI("ble_client_lambda", "Sending auth to Tethercell ${tethercell_number}");
        - ble_client.ble_write: # send the authentication PIN to activate the service announcement
            id: tethercell_device_${tethercell_number}
            service_uuid: ${uuid.service}
            characteristic_uuid: ${uuid.authorization}
            value: !lambda |-
              uint32_t val = strtoul("${tethercell_pin}", nullptr, 10);
              return std::vector<uint8_t>{
                (uint8_t)((val >> 24) & 0xFF),
                (uint8_t)((val >> 16) & 0xFF),
                (uint8_t)((val >> 8) & 0xFF),
                (uint8_t)(val & 0xFF)
              };
    on_disconnect:
      then:
        - lambda: |-
            ESP_LOGI("ble_client_lambda", "Client disconnected from Tethercell ${tethercell_number}");
            
sensor:
  - platform: ble_client
    type: characteristic
    ble_client_id: tethercell_device_${tethercell_number}
    name: "Family"
    service_uuid: ${uuid.service}
    characteristic_uuid: ${uuid.family}
    icon: 'variable'
  - platform: ble_client
    type: characteristic
    ble_client_id: tethercell_device_${tethercell_number}
    name: "FET State"
    service_uuid: ${uuid.service}
    characteristic_uuid: ${uuid.fet_state}
    icon: 'variable'
  - platform: ble_client
    type: characteristic
    ble_client_id: tethercell_device_${tethercell_number}
    name: "Battery voltage"
    service_uuid: ${uuid.service}
    characteristic_uuid: ${uuid.battery_voltage}
    icon: 'variable'
  - platform: ble_client
    type: characteristic
    ble_client_id: tethercell_device_${tethercell_number}
    name: "Timers"
    service_uuid: ${uuid.service}
    characteristic_uuid: ${uuid.timers}
    icon: 'variable'
  - platform: ble_client
    type: characteristic
    ble_client_id: tethercell_device_${tethercell_number}
    name: "Timer access index"
    service_uuid: ${uuid.service}
    characteristic_uuid: ${uuid.timer_access_index}
    icon: 'variable'
  - platform: ble_client
    type: characteristic
    ble_client_id: tethercell_device_${tethercell_number}
    name: "Battery Voltage Most Recent Index"
    service_uuid: ${uuid.service}
    characteristic_uuid: ${uuid.Battery Voltage Most Recent Index}
    icon: 'variable'
  - platform: ble_client
    type: characteristic
    ble_client_id: tethercell_device_${tethercell_number}
    name: "Battery Voltage History"
    service_uuid: ${uuid.service}
    characteristic_uuid: ${uuid.battery_voltage_history}
    icon: 'variable'
  - platform: ble_client
    type: characteristic
    ble_client_id: tethercell_device_${tethercell_number}
    name: "Password"
    service_uuid: ${uuid.service}
    characteristic_uuid: ${uuid.password}
    icon: 'variable'
  - platform: ble_client
    type: characteristic
    ble_client_id: tethercell_device_${tethercell_number}
    name: "Device Name"
    service_uuid: ${uuid.service}
    characteristic_uuid: ${uuid.device_name}
    icon: 'variable'
  - platform: ble_client
    type: characteristic
    ble_client_id: tethercell_device_${tethercell_number}
    name: "UTC Time"
    service_uuid: ${uuid.service}
    characteristic_uuid: ${uuid.utc_time}
    icon: 'variable'
  - platform: ble_client
    type: characteristic
    ble_client_id: tethercell_device_${tethercell_number}
    name: "Advertising Period in s"
    service_uuid: ${uuid.service}
    characteristic_uuid: ${uuid.advertising_period}
    icon: 'variable'

switch:
  - platform: template
    name: "Tethercell ${tethercell_number} FET"
    optimistic: true
    icon: mdi:battery-bluetooth
    turn_on_action:
      - ble_client.ble_write: # send authentication pin
          id: tethercell_device_${tethercell_number}
          service_uuid: ${uuid.service}
          characteristic_uuid: ${uuid.authorization}
          value: !lambda |-
            uint32_t val = strtoul("${tethercell_pin}", nullptr, 10);
            return std::vector<uint8_t>{
              (uint8_t)((val >> 24) & 0xFF),
              (uint8_t)((val >> 16) & 0xFF),
              (uint8_t)((val >> 8) & 0xFF),
              (uint8_t)(val & 0xFF)
            };
      - ble_client.ble_write: # send fet state on
          id: tethercell_device_${tethercell_number}
          service_uuid: ${uuid.service}
          characteristic_uuid: ${uuid.fet_state}
          value: [0x01]
      - lambda: |-
            ESP_LOGI("ble_client_lambda", "Send FET ON to Tethercell ${tethercell_number}");
    turn_off_action:
      - ble_client.ble_write: # send authentication pin
          id: tethercell_device_${tethercell_number}
          service_uuid: ${uuid.service}
          characteristic_uuid: ${uuid.authorization}
          value: !lambda |-
            uint32_t val = strtoul("${tethercell_pin}", nullptr, 10);
            return std::vector<uint8_t>{
              (uint8_t)((val >> 24) & 0xFF),
              (uint8_t)((val >> 16) & 0xFF),
              (uint8_t)((val >> 8) & 0xFF),
              (uint8_t)(val & 0xFF)
            };
      - ble_client.ble_write: # send fet state off
          id: tethercell_device_${tethercell_number}
          service_uuid: ${uuid.service}
          characteristic_uuid: ${uuid.fet_state}
          value: [0x00]
      - lambda: |-
            ESP_LOGI("ble_client_lambda", "Send FET OFF to Tethercell ${tethercell_number}");
